In [ ]:




duration_days = np.random.randint(180, 900)

end_date = start_date + timedelta(days=duration_days)

In [97]:

# GENEATE POJECTS

# Import required modules
import numpy as np
import pandas as pd
from faker import Faker
from datetime import timedelta

fake = Faker()
# create a lit with project names
project_names = [
    "Dragon Rider",
    "Bear in City",
    "Imaginary Bonds",
    "Galactic Guardians",
    "Sheep Quest",
    "Frozen History",
    "Teddy Bear",
    "Titan Rising",
    "Mystic Forest",
    "Solar Frontier"
]
# empty container for the projects data
projects = []

# studio names 
studio_names =[
            "Miller-Jones Entertainment",
            "Apex Studios",
            "Smith Media",
            "Positive Studios",
            "Quantum Entertainment",
            "Para-Mountain Entertainment",
            "Trixify Media House",
            "Blue Potato Entertainment",
            "Compass Media",
            "Story Store Studios"
        ]

# assign the random variable to studio names for assignment
random_studio = np.random.permutation(studio_names)
# loop using enumerate to get the index along with the value to help in creating project_id
for i, name in enumerate(project_names):
    project_type = np.random.choice([
            "Feature Film",
            "Streaming Series"
        ])
    # generate fake date range from 3 years till today
    start_date = fake.date_between(
        start_date="-3y",
        end_date="today"
    )
    if project_type == "Feature Film":
        budget = np.random.randint(80, 250)
        #duration of days the project will take/bidded days
        duration_days = np.random.randint(300, 900)
    else:
        budget = np.random.randint(15, 80)
        duration_days = np.random.randint(90, 500)
    end_date = start_date + timedelta(days=duration_days)
    
    # create condition for the project status 
    today = pd.Timestamp.today().date()
    if end_date < today:
        status = "Completed"
    else:
        status = "In Progress"

    projects.append({
        "project_id": f"P{i+1:03}",
        "project_name": name,
        "project_type": project_type,
        # random studio with the index of var i so that each studio is assigned once to a project
        "client": random_studio[i],
        "budget_million_usd": budget,
        "start_date": start_date,
        "end_date": end_date,
        "status": status
    })

projects_df = pd.DataFrame(projects)

projects_df

,project_id,project_name,project_type,client,budget_million_usd,start_date,end_date,status
0,P001,Dragon Rider,Feature Film,Positive Studios,217,2025-06-20,2026-06-07,Completed
1,P002,Bear in City,Feature Film,Miller-Jones Entertainment,113,2024-01-27,2026-06-22,In Progress
2,P003,Imaginary Bonds,Streaming Series,Story Store Studios,33,2025-12-27,2027-02-13,In Progress
3,P004,Galactic Guardians,Feature Film,Para-Mountain Entertainment,106,2024-02-11,2025-04-29,Completed
4,P005,Sheep Quest,Feature Film,Blue Potato Entertainment,115,2024-10-20,2026-11-09,In Progress
5,P006,Frozen History,Streaming Series,Smith Media,17,2023-10-03,2024-03-23,Completed
6,P007,Teddy Bear,Feature Film,Compass Media,246,2025-08-10,2027-01-14,In Progress
7,P008,Titan Rising,Feature Film,Apex Studios,160,2025-10-15,2027-09-23,In Progress
8,P009,Mystic Forest,Streaming Series,Trixify Media House,54,2024-05-01,2025-07-13,Completed
9,P010,Solar Frontier,Streaming Series,Quantum Entertainment,75,2023-06-20,2024-03-26,Completed

In [98]:
# write to csv
projects_df.to_csv("..\data\projects.csv", index=False)

<>:2: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:2: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\Jay\AppData\Local\Temp\ipykernel_16932\2757999916.py:2: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  projects_df.to_csv("..\data\projects.csv", index=False)

In [99]:
df = pd.read_csv("..\data\projects.csv")
df

<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\Jay\AppData\Local\Temp\ipykernel_16932\1355173906.py:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  df = pd.read_csv("..\data\projects.csv")

,project_id,project_name,project_type,client,budget_million_usd,start_date,end_date,status
0,P001,Dragon Rider,Feature Film,Positive Studios,217,2025-06-20,2026-06-07,Completed
1,P002,Bear in City,Feature Film,Miller-Jones Entertainment,113,2024-01-27,2026-06-22,In Progress
2,P003,Imaginary Bonds,Streaming Series,Story Store Studios,33,2025-12-27,2027-02-13,In Progress
3,P004,Galactic Guardians,Feature Film,Para-Mountain Entertainment,106,2024-02-11,2025-04-29,Completed
4,P005,Sheep Quest,Feature Film,Blue Potato Entertainment,115,2024-10-20,2026-11-09,In Progress
5,P006,Frozen History,Streaming Series,Smith Media,17,2023-10-03,2024-03-23,Completed
6,P007,Teddy Bear,Feature Film,Compass Media,246,2025-08-10,2027-01-14,In Progress
7,P008,Titan Rising,Feature Film,Apex Studios,160,2025-10-15,2027-09-23,In Progress
8,P009,Mystic Forest,Streaming Series,Trixify Media House,54,2024-05-01,2025-07-13,Completed
9,P010,Solar Frontier,Streaming Series,Quantum Entertainment,75,2023-06-20,2024-03-26,Completed

In [108]:
(df["end_date"]>df["start_date"]).all()

np.True_